### ISSUE TITLE
DGS Plugin Update for Intellij v.2023.1

### ISSUE THREAD

**Issue by abftapi** [Netflix/dgs-intellij-plugin#59]
Please update the dgs intellij plugin in order to work it with the newest Intellij Idea version, which is at the moment 2023.1
Plugin version: 1.2.6
MacBook Pro M1 pro chip
MacOS: 13.3.1 (22E261)

There is an error occurred when the intellij version 2023.1 was installed.

Getting the following error:

`java.lang.IncompatibleClassChangeError: Method 'com.intellij.lang.jsgraphql.schema.GraphQLSchemaProvider com.intellij.lang.jsgraphql.schema.GraphQLSchemaProvider.getInstance(com.intellij.openapi.project.Project)' must be Methodref constant
	at com.netflix.dgs.plugin.services.internal.GraphQLSchemaRegistry.getRegistry(GraphQLSchemaRegistry.java:122)
	at com.netflix.dgs.plugin.services.internal.GraphQLSchemaRegistry.psiForSchemaType(GraphQLSchemaRegistry.java:41)
	at com.netflix.dgs.plugin.services.DgsComponentProcessor.processDataFetcher(DgsDataProcessor.kt:159)
	at com.netflix.dgs.plugin.services.DgsComponentProcessor.process(DgsDataProcessor.kt:40)
	at com.netflix.dgs.plugin.services.internal.DgsServiceImpl.lambda$getDgsComponentIndex$0(DgsServiceImpl.java:99)
	at com.intellij.psi.stubs.StubProcessingHelperBase.processStubsInFile(StubProcessingHelperBase.java:74)
	at com.intellij.psi.stubs.StubIndexEx.lambda$processElements$4(StubIndexEx.java:146)
	at com.intellij.psi.stubs.StubIndexEx.processElements(StubIndexEx.java:210)
	at com.intellij.psi.stubs.StubIndex.processElements(StubIndex.java:53)
	at com.netflix.dgs.plugin.services.internal.DgsServiceImpl.lambda$getDgsComponentIndex$1(DgsServiceImpl.java:96)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at com.netflix.dgs.plugin.services.internal.DgsServiceImpl.getDgsComponentIndex(DgsServiceImpl.java:95)
	at com.netflix.dgs.plugin.navigation.SchemaToDataFetcherMarkerProvider.collectNavigationMarkers(SchemaToDataFetcherMarkerProvider.kt:41)
	at com.intellij.codeInsight.daemon.RelatedItemLineMarkerProvider.collectNavigationMarkers(RelatedItemLineMarkerProvider.java:35)
	at com.intellij.codeInsight.daemon.RelatedItemLineMarkerProvider.collectSlowLineMarkers(RelatedItemLineMarkerProvider.java:27)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.queryProviders(LineMarkersPass.java:223)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.lambda$doCollectInformation$3(LineMarkersPass.java:104)
	at com.intellij.codeInsight.daemon.impl.Divider.divideInsideAndOutsideInOneRoot(Divider.java:95)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.doCollectInformation(LineMarkersPass.java:99)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:57)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$1(PassExecutorService.java:382)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1102)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:374)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:604)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:603)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:373)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:349)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:229)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:187)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:347)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:181)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
`

**Comment by abftapi** [comment]
Yes, it works. I've already updated. Thank you.
