### ISSUE TITLE
Plugin error (1.2.6-1.2.8) with IntelliJ IntelliJ IDEA 2023.1.2 (Ultimate Edition)

### ISSUE THREAD

**Issue by thugec** [Netflix/dgs-intellij-plugin#66]
```
java.lang.IncompatibleClassChangeError: Method 'com.intellij.lang.jsgraphql.schema.GraphQLSchemaProvider com.intellij.lang.jsgraphql.schema.GraphQLSchemaProvider.getInstance(com.intellij.openapi.project.Project)' must be Methodref constant
	at com.netflix.dgs.plugin.services.internal.GraphQLSchemaRegistry.getRegistry(GraphQLSchemaRegistry.java:122)
	at com.netflix.dgs.plugin.services.internal.GraphQLSchemaRegistry.psiForSchemaType(GraphQLSchemaRegistry.java:41)
	at com.netflix.dgs.plugin.services.DgsComponentProcessor.processDataFetcher(DgsDataProcessor.kt:159)
	at com.netflix.dgs.plugin.services.DgsComponentProcessor.process(DgsDataProcessor.kt:40)
	at com.netflix.dgs.plugin.services.internal.DgsServiceImpl.lambda$getDgsComponentIndex$3(DgsServiceImpl.java:121)
	at com.intellij.util.SmartList.forEach(SmartList.java:349)
	at com.netflix.dgs.plugin.services.internal.DgsServiceImpl.lambda$getDgsComponentIndex$4(DgsServiceImpl.java:118)
	at com.intellij.util.io.PersistentEnumeratorBase.lambda$iterateData$1(PersistentEnumeratorBase.java:413)
	at com.intellij.util.io.keyStorage.AppendableStorageBackedByResizableMappedFile.lambda$processAll$3(AppendableStorageBackedByResizableMappedFile.java:114)
	at com.intellij.util.io.PagedFileStorage.lambda$readInputStream$1(PagedFileStorage.java:122)
	at com.intellij.util.io.PagedFileStorage.useChannel(PagedFileStorage.java:152)
	at com.intellij.util.io.PagedFileStorage.readInputStream(PagedFileStorage.java:120)
	at com.intellij.util.io.ResizeableMappedFile.readInputStream(ResizeableMappedFile.java:272)
	at com.intellij.util.io.keyStorage.AppendableStorageBackedByResizableMappedFile.processAll(AppendableStorageBackedByResizableMappedFile.java:101)
	at com.intellij.util.io.PersistentEnumeratorBase.doIterateData(PersistentEnumeratorBase.java:425)
	at com.intellij.util.io.PersistentEnumeratorBase.iterateData(PersistentEnumeratorBase.java:413)
	at com.intellij.util.io.PersistentMapImpl.processKeys(PersistentMapImpl.java:493)
	at com.intellij.util.indexing.impl.ValueContainerMap.processKeys(ValueContainerMap.java:73)
	at com.intellij.util.indexing.impl.MapIndexStorage.doProcessKeys(MapIndexStorage.java:368)
	at com.intellij.util.indexing.impl.storage.VfsAwareMapIndexStorage.processKeys(VfsAwareMapIndexStorage.java:125)
	at com.intellij.util.indexing.impl.storage.TransientChangesIndexStorage.processKeys(TransientChangesIndexStorage.java:139)
	at com.intellij.util.indexing.storage.MapReduceIndexBase.lambda$processAllKeys$0(MapReduceIndexBase.java:52)
	at com.intellij.util.ConcurrencyUtil.withLock(ConcurrencyUtil.java:233)
	at com.intellij.util.indexing.storage.MapReduceIndexBase.processAllKeys(MapReduceIndexBase.java:51)
	at com.intellij.indexing.composite.CompositeInvertedIndexBase.processAllKeys(CompositeInvertedIndexBase.java:119)
	at com.intellij.psi.stubs.StubIndexEx.lambda$processAllKeys$8(StubIndexEx.java:282)
	at com.intellij.util.indexing.IndexUpToDateCheckIn.disableUpToDateCheckIn(IndexUpToDateCheckIn.kt:15)
	at com.intellij.util.indexing.FileBasedIndexEx.disableUpToDateCheckIn(FileBasedIndexEx.java:771)
	at com.intellij.psi.stubs.StubIndexEx.lambda$processAllKeys$9(StubIndexEx.java:281)
	at com.intellij.util.indexing.diagnostic.IndexAccessValidator.validate(IndexAccessValidator.java:42)
	at com.intellij.psi.stubs.StubIndexEx.processAllKeys(StubIndexEx.java:281)
	at com.intellij.psi.stubs.StubIndex.processAllKeys(StubIndex.java:67)
	at com.netflix.dgs.plugin.services.internal.DgsServiceImpl.getDgsComponentIndex(DgsServiceImpl.java:116)
	at com.netflix.dgs.plugin.provider.DgsComponentsRootNode.getChildren(DgsProjectStructureProvider.kt:73)
	at com.netflix.dgs.plugin.provider.DgsComponentsRootNode.update(DgsProjectStructureProvider.kt:60)
	at com.intellij.ide.util.treeView.PresentableNodeDescriptor.getUpdatedPresentation(PresentableNodeDescriptor.java:78)
	at com.intellij.ide.util.treeView.PresentableNodeDescriptor.update(PresentableNodeDescriptor.java:30)
	at com.intellij.ui.tree.StructureTreeModel$Node.update(StructureTreeModel.java:458)
	at com.intellij.ui.tree.StructureTreeModel$Node.<init>(StructureTreeModel.java:439)
	at com.intellij.ui.tree.StructureTreeModel$Node.<init>(StructureTreeModel.java:432)
	at com.intellij.ui.tree.StructureTreeModel.getValidChildren(StructureTreeModel.java:390)
	at com.intellij.ui.tree.StructureTreeModel.validateChildren(StructureTreeModel.java:299)
	at com.intellij.ui.tree.StructureTreeModel.getNode(StructureTreeModel.java:293)
	at com.intellij.ui.tree.StructureTreeModel.getChildren(StructureTreeModel.java:313)
	at com.intellij.ui.tree.AsyncTreeModel$CmdGetChildren.getNode(AsyncTreeModel.java:545)
	at com.intellij.ui.tree.AsyncTreeModel$Command.get(AsyncTreeModel.java:440)
	at com.intellij.ui.tree.AsyncTreeModel$Command.get(AsyncTreeModel.java:406)
	at com.intellij.util.concurrency.Invoker$Task.run(Invoker.java:319)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1154)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runInReadActionWithWriteActionPriority$0(ProgressIndicatorUtils.java:75)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runActionAndCancelBeforeWrite(ProgressIndicatorUtils.java:158)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runWithWriteActionPriority$1(ProgressIndicatorUtils.java:115)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:66)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:188)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:608)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:683)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:639)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:607)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:175)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:66)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runWithWriteActionPriority(ProgressIndicatorUtils.java:112)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:75)
	at com.intellij.util.concurrency.Invoker.invokeSafely(Invoker.java:205)
	at com.intellij.util.concurrency.Invoker.lambda$offerSafely$0(Invoker.java:183)
	at com.intellij.util.concurrency.Invoker$Background.lambda$offer$0(Invoker.java:487)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:241)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:31)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.execute(BoundedTaskExecutor.java:214)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:212)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:203)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by esfomeado** [comment]
Can you add replication steps please?

**Comment by thugec** [comment]
> Can you add replication steps please?

Ok seems like it is not longer a problem, at least for today after reinstalling of the plugin.
But the reproduction steps were pretty straightforward:
1. Open IDEA with installed plugin or simply install the plugin
2. See the report (IDEA suggested to disable plugin and report to the vendor) 
  When the plugin was not disabled, it made few functions of the IDE not working

**Comment by spellew** [comment]
Hi @thugec, it looks like this is no longer an issue. Can we go ahead and close it?

**Comment by srinivasankavitha** [comment]
I'll close this issue, please reopen if needed.
